-- MySQL Script generated by MySQL Workbench
-- Thu Feb  4 17:53:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteka` DEFAULT CHARACTER SET utf8 ;
USE `biblioteka` ;

-- -----------------------------------------------------
-- Table `biblioteka`.`knjige`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`knjige` (
  `id` INT NOT NULL,
  `naslov` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`zanr` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`clanovi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`clanovi` (
  `id` INT NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `adresa` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`zaduzenje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`zaduzenje` (
  `id` INT NOT NULL,
  `datum` DATE NOT NULL,
  `vratio` TINYINT(1) NULL DEFAULT 0,
  `clanovi_id` INT NOT NULL,
  `knjige_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clanovi_id`, `knjige_id`),
  INDEX `fk_zaduzenje_clanovi1_idx` (`clanovi_id` ASC) VISIBLE,
  INDEX `fk_zaduzenje_knjige1_idx` (`knjige_id` ASC) VISIBLE,
  CONSTRAINT `fk_zaduzenje_clanovi1`
    FOREIGN KEY (`clanovi_id`)
    REFERENCES `biblioteka`.`clanovi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zaduzenje_knjige1`
    FOREIGN KEY (`knjige_id`)
    REFERENCES `biblioteka`.`knjige` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`pisac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`pisac` (
  `id` INT NOT NULL,
  `ime_prezime` VARCHAR(45) NULL,
  `bio` TEXT NULL,
  `god_rodj` YEAR NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`knjige_has_pisac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`knjige_has_pisac` (
  `knjige_id` INT NOT NULL,
  `pisac_id` INT NOT NULL,
  PRIMARY KEY (`knjige_id`, `pisac_id`),
  INDEX `fk_knjige_has_pisac_pisac1_idx` (`pisac_id` ASC) VISIBLE,
  INDEX `fk_knjige_has_pisac_knjige_idx` (`knjige_id` ASC) VISIBLE,
  CONSTRAINT `fk_knjige_has_pisac_knjige`
    FOREIGN KEY (`knjige_id`)
    REFERENCES `biblioteka`.`knjige` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_knjige_has_pisac_pisac1`
    FOREIGN KEY (`pisac_id`)
    REFERENCES `biblioteka`.`pisac` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteka`.`knjige_has_zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteka`.`knjige_has_zanr` (
  `knjige_id` INT NOT NULL,
  `zanr_id` INT NOT NULL,
  PRIMARY KEY (`knjige_id`, `zanr_id`),
  INDEX `fk_knjige_has_zanr_zanr1_idx` (`zanr_id` ASC) VISIBLE,
  INDEX `fk_knjige_has_zanr_knjige1_idx` (`knjige_id` ASC) VISIBLE,
  CONSTRAINT `fk_knjige_has_zanr_knjige1`
    FOREIGN KEY (`knjige_id`)
    REFERENCES `biblioteka`.`knjige` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_knjige_has_zanr_zanr1`
    FOREIGN KEY (`zanr_id`)
    REFERENCES `biblioteka`.`zanr` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
